language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'

before_script:
  - composer install --no-interaction

script:
  - ./bin/phpcs --standard=PSR12 -p ./src ./features
  - ./bin/behat -f progress

cache:
  directories:
    - $HOME/.composer/cache
